version: '3'

services:
  api:
    container_name: gin_api
    build: docker/go/Dockerfile
    ports:
      - 3000:3000
    links:
      - mysql
    tty:
      true
    volumes:
	  - ./app:/go/src/api
	depends_on:
	  - mysql	

   mysql:
	container_name: mysql
	build: docker/mysql/Dockerfile
	hostname: mysql
	ports: 
	  - "3306:3306"
	env_file: 
	  - docker/mysql/env
	